#@> Executed from:
#@>   function hygrave:run/config

##
tellraw @s ""

## Title & Tips
tellraw @s [{"translate": "hygrave.config_title","fallback": "§b§lHyper§6§lGrave §7§lConfigs"}, " ", {\
  "translate": "hygrave.config_tips",\
  "fallback": "§eℹ",\
  "hover_event": {\
    "action": "show_text",\
    "value": {\
      "translate": "hygrave.config_tips.1",\
      "fallback": "§eHyperGrave is super customizable, but its configs are mostly generic §6(meaning instead of having multiple configs, it has one config that can do what these configs can do)§e. This means that it might be harder for you to find what you want. Here are things you might've wanted to do:\n\n§bMake players unable to loot graves that wasn't generated by them\n§fTo do that, go to Requirements / Generating Graves / Non-Owners and set the field Gamerules to §cS§f, §cA§f, §cC§f.\n\n§bKeep certain items in the player's inventory or remove them from the player's inventory\n§fTo do that, use the configs Item Distribution and Slot Distribution."\
    }\
  }\
}]


##
tellraw @s ""

## Main Menu
tellraw @s [\
  "",\
  {\
    "translate": "§7[%s§7|%s§7|%s§7]",\
    "with": [\
      {\
        "translate": "hygrave.config.main_menu.requirements",\
        "fallback": "§l  §r§bRequirements  ",\
        "hover_event": {\
          "action": "show_text",\
          "value": {\
            "translate": "hygrave.config_page_open_description.requirements",\
            "fallback": "All configs about requirements to accomplish certain tasks like looting graves or generating graves\nClick to open page 'Requirements'."\
            }\
          },\
        "click_event": {\
          "action": "run_command",\
          "command": "/function hygrave:internal/config/open_page/requirements"\
        }\
      },\
      {\
        "translate": "hygrave.config.main_menu.general",\
        "fallback": "  §bGeneral§l  ",\
        "hover_event": {\
          "action": "show_text",\
          "value": {\
            "translate": "hygrave.config_page_open_description.dropped_contents",\
            "fallback": "All unrelated configs"\
            }\
          },\
        "click_event": {\
          "action": "run_command",\
          "command": "/function hygrave:internal/config/open_page/general"\
        }\
      },\
      {\
        "translate": "hygrave.config.main_menu.graves",\
        "fallback": "  §bGraves  ",\
        "hover_event": {\
          "action": "show_text",\
          "value": {\
            "translate": "hygrave.config_page_open_description.graves",\
            "fallback": "All configs about graves in general\nClick to open page 'Graves'."\
            }\
          },\
        "click_event": {\
          "action": "run_command",\
          "command": "/function hygrave:internal/config/open_page/graves"\
        }\
      }\
    ]\
  }\
]

tellraw @s [\
  "\n",\
  {\
    "translate": "§7[%s§7|%s§7]",\
    "with": [\
      {\
        "translate": "hygrave.config.main_menu.dropped_contents",\
        "fallback": " §bDropped Contents ",\
        "hover_event": {\
          "action": "show_text",\
          "value": {\
            "translate": "hygrave.config_page_open_description.dropped_contents",\
            "fallback": "All configs about dropped items and XP from graves\nClick to open page 'Dropped Contents'."\
            }\
          },\
        "click_event": {\
          "action": "run_command",\
          "command": "/function hygrave:internal/config/open_page/dropped_contents"\
        }\
      },\
      {\
        "translate": "hygrave.config.main_menu.grave_interaction",\
        "fallback": " §bGrave Interaction ",\
        "hover_event": {\
          "action": "show_text",\
          "value": {\
            "translate": "hygrave.config_page_open_description.grave_interaction",\
            "fallback": "All configs about interacting with graves\nClick to open page 'Grave Interaction'."\
            }\
          },\
        "click_event": {\
          "action": "run_command",\
          "command": "/function hygrave:internal/config/open_page/grave_interaction"\
        }\
      }\
    ]\
  }\
]

tellraw @s [\
  "\n",\
  {\
    "translate": "§7[%s§7]",\
    "with": [\
      {\
        "translate": "hygrave.config.main_menu.grave_appearance",\
        "fallback": "        §bGrave Style & Appearance        ",\
        "hover_event": {\
          "action": "show_text",\
          "value": {\
            "translate": "hygrave.config_page_open_description.grave_appearance",\
            "fallback": "All configs about styles and appearances of graves\nClick to open page 'Grave Style & Appearance'."\
            }\
          },\
        "click_event": {\
          "action": "run_command",\
          "command": "/function hygrave:internal/config/open_page/grave_appearance"\
        }\
      }\
    ]\
  }\
]

##
tellraw @s ""